version: '3.5'

services:
  ###################
  # PROXY
  ###################
  traefik:
   image: "traefik:v2.5"
   container_name: "traefik"
   hostname: "traefik"
   command:
     - --log.level=DEBUG
     - --api.dashboard=true
     - --api.insecure=true
     - --providers.docker=true
     - --entryPoints.web.forwardedHeaders.insecure=true
     - --entrypoints.web.address=:80
   labels:
     - "traefik.enable=true"
   ports:
     - "80:80"
     - "8080:8080"
   volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
   networks:
     - gravitee-net
#  ###################
#  # GRAVITEE APIM
#  ###################
  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.10.2}
   container_name: gio_apim_elasticsearch
   restart: always
   volumes:
     - ./data/apim-elasticsearch:/usr/share/elasticsearch/data
   environment:
     - http.host=0.0.0.0
     - transport.host=0.0.0.0
     - xpack.security.enabled=false
     - xpack.monitoring.enabled=false
     - cluster.name=elasticsearch
     - bootstrap.memory_lock=true
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   ulimits:
     memlock:
       soft: -1
       hard: -1
     nofile: 65536
   ports:
     - "9200:9200"
   networks:
     - gravitee-net

  gateway:
   image: graviteeio/apim-gateway:3.12.1
   restart: always
   ports:
     - "8082"
     # - "8082"
   labels:
     - "traefik.enable=true"
   depends_on:
     - mongodb
     - redis
     - elasticsearch
   volumes:
     - ./data/logs/apim-gateway:/opt/graviteeio-gateway/logs
   environment:
      - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200
      - ./config/gravitee/gateway/config:/opt/graviteeio-gateway/config
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
   networks:
     - gravitee-net

  management_api:
   image: graviteeio/apim-management-api:3.15.4
   container_name: gio_apim_management_api
   restart: always
   ports:
     - "8083:8083"
   links:
     - mongodb
     - elasticsearch
   depends_on:
     - mongodb
     - elasticsearch
   volumes:
     - ./data/logs/apim-management-api:/opt/graviteeio-management-api/logs
   environment:
     - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
     - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
     - gravitee_email_enabled=true
     - gravitee_email_host=fakesmtp
     - gravitee_email_port=1025
   networks:
     - gravitee-net

  management_ui:
   image: graviteeio/apim-management-ui:3.15.4
   container_name: gio_apim_management_ui
   restart: always
   ports:
     - "8084:8080"
   depends_on:
     - management_api
   environment:
     - MGMT_API_URL=http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/
   volumes:
     - ./data/logs/apim-management-ui:/var/log/nginx
   networks:
     - gravitee-net

  portal_ui:
   image: graviteeio/apim-portal-ui:3.15.4
   container_name: gio_apim_portal_ui
   restart: always
   ports:
     - "8085:8080"
   depends_on:
     - management_api
   environment:
     - PORTAL_API_URL=http://localhost:8083/portal/environments/DEFAULT
   volumes:
     - ./data/logs/apim-portal-ui:/var/log/nginx
   networks:
     - gravitee-net

  fakesmtp:
   image: reachfive/fake-smtp-server:0.8.1
   container_name: fake_smtp
   ports:
     - "1080:1080"
     - "1025:1025"
   networks:
     - gravitee-net

  mongodb:
    image: mongo:${MONGODB_VERSION:-3.6}
    container_name: gio_apim_mongodb
    restart: always
    volumes:
      - ./data/data-mongo:/data/db
      - ./data/apim-mongodb:/var/log/mongodb
    networks:
      - gravitee-net

  redis:
    image: redis:6.2
    container_name: rate-limit-redis
    restart: always
    volumes:
      - ./data/redis:/data
    command: --requirepass toto
    ports:
      - "0.0.0.0:6379:6379"
    networks:
      - gravitee-net

networks:
  gravitee-net:
    name: gravitee-net

volumes:
  data-elasticsearch:
  data-mongo: